name: Android CI with GMD

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  android-ci:
    runs-on: macos-latest

    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: actions/checkout@v2

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Run instrumented tests with GMD
        run: ./gradlew pixel6Api31DemoDebugAndroidTest  -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"
      - name: Upload Gradle Managed device test results
        uses: actions/upload-artifact@v3.1.1
        with:
          name: testResults
          path: app/build/reports/androidTests/managedDevice/allDevices/index.html
